version: "3.8"

services:
  db:
    image: "postgres:14-alpine"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
