GET http://localhost:8080/room/rooms
Accept: application/json

###
//info
POST http://localhost:8080/api/create
Content-Type: application/json
Accept: application/json

{
  "roomNumber": "999",
  "roomName": "gym"
}

###
POST http://localhost:8080/device/create-device
Content-Type: application/json
Accept: application/json

{
  "name": "Laptop",
  "brand": "HP",
  "ean" : "12341521ADS",
  "category": "Streaming"
}

###

PUT http://localhost:8080/device/update-device/1
Content-Type: application/json

{
  "name": "HD Camera",
  "brand": "XIOAMI",
  "ean" : "1231252asda",
  "category": "MEDIA"
}
###
GET http://localhost:8080/device/sortByCategories/STREAMING

###

GET http://localhost:8080/device/getAllCategories
###

DELETE http://localhost:8080/api/delete/5AHIF
Content-Type: application/json
###


DELETE http://localhost:8080/room/delete/AULA
Content-Type: application/json
###

PUT http://localhost:8080/api/update/5BHIF
Content-Type: application/json

{
  "roomNumber": 1231,
  "roomName": "Hund"
}

###

POST http://localhost:8080/api/create-user
Content-Type: application/json
Accept: application/json

{
  "name":"Felix",
  "passwordHash": "1249a4589340"

}

###

DELETE http://localhost:8080/users/delete/1
###

POST http://localhost:8080/install/create-installat
Content-Type: application/json
Accept: application/json

{
  "installDate": "15/12/2022",
  "removeDate": "15/12/2022",
  "description": "hahahahhaha hase",
  "u_id": "3",
  "r_id": "1001",
  "d_id": "4"
}

###
GET http://localhost:8080/installAt/installs
Accept: application/json

###

GET http://localhost:8080/api/getInstallsByRoom/1001
Accept: application/json

###
GET http://localhost:8080/install/room/1001
Accept: application/json
###
DELETE http://localhost:8080/install/delete/2000
###
GET http://localhost:8080/device/freeDevices

