GET http://localhost:8080/api/rooms
Accept: application/json

###
//info
POST http://localhost:8080/api/create
Content-Type: application/json
Accept: application/json

{
  "roomNumber": "999",
  "roomName": "gym"
}

###

DELETE http://localhost:8080/api/delete/63
Content-Type: application/json
###

PUT http://localhost:8080/api/update/1002
Content-Type: application/json

{
  "roomNumber": 187,
  "roomName": "K03"
}

###

POST http://localhost:8080/users/create
Content-Type: application/x-www-form-urlencoded
Accept: application/json

name=Batuhan&passwordHash=Batu123

###

DELETE http://localhost:8080/users/delete/1