@startuml

class Device{
  int serialNumber
  String name
  String brand
  DateTime installedFrom
  DateTime installedTo
}

class Room{
   String roomName
   int roomNumber
}
class User
{
String name
string password
}

Device "1 .. *" --- "1" Room
Device "1 .. *" --- "1" User

@enduml