@startuml

class Device{
  int serialNumber
  String name
  String brand
}

class Room{
   String roomName
   int roomNumber
}
class User
{
    String name
    String password
}

class installedAt{
    installDate : LocalDate
    removeDate : LocalDate
    description : String
}

Device "1 .. *" - "1" installedAt
Room "1 .. *" -left- "1" installedAt
User "1 .. *" -- "1" installedAt


@enduml