
@startuml
left to right direction
skinparam packageStyle rectangle
actor user
rectangle manager {
  user -- (install device)
  user -- (deinstall device)
  user -- (update device)
  user -- (list devices)
}
@enduml

