
@startuml
left to right direction
skinparam packageStyle rectangle
actor User
actor Authentication
rectangle manager {
  User -- (install device)
  (install device) .> (deinstall device) : include
  (install device) .> (view devices) : include
  (install device) .> (refactor devic) : include
  User -- (login)
  (login) -- Authentication
}
@enduml

